import './globals.css'
import { Inter } from "next/font/google";
import Header from "../components/Header";
import Footer from "../components/Footer"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'BikeVision',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
